version: '3'
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: AppleSucks
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "9004:80"
    volumes:
      - ./app:/app
    restart: always
volumes:
  db_data:
